### ISSUE TITLE
problems about '/peer'

### ISSUE THREAD

**Issue by beyondgcy** [adnanafik/tiny_coin#1]
You code give me a lot help.
Can you tell me how to set the 'node_url', I want to get the node "127.0.0.1:5000" connect to the node "127.0.0.1:5001" by using the Postman. but I failed.

**Comment by adnanafik** [comment]
sorry to getting back that late, following is the way you would use /peer

http://127.0.0.1:5000/peer?node_url=http://127.0.0.1:5001

I've added more code now that supports proof of work, Bitcoin compatible address for every node you will run, it now signs the transaction that can be verified by other node. I will add more support soon.
